"use strict";

const TASKFACTORY_NAMEID_CRYPTOKITTIES      = 'cryptokitties';

const TASK_NAMEID_INITKITTY                 = 'initkitty';
const TASK_NAMEID_INITKITTYIMG              = 'initkittyimg';

exports.TASKFACTORY_NAMEID_CRYPTOKITTIES    = TASKFACTORY_NAMEID_CRYPTOKITTIES;

exports.TASK_NAMEID_INITKITTY               = TASK_NAMEID_INITKITTY;
exports.TASK_NAMEID_INITKITTYIMG            = TASK_NAMEID_INITKITTYIMG;